package ca.csf.mobile2.tp2.question

import android.annotation.SuppressLint
import android.support.v7.app.AppCompatActivity
import android.widget.Button
import android.widget.ProgressBar
import android.widget.TextView
import ca.csf.mobile2.tp2.R
import ca.csf.mobile2.tp2.databinding.ActivityQuestionBinding
import org.androidannotations.annotations.*
import java.util.*

@SuppressLint("Registered") //Reason : Generated by Android Annotations
@DataBound
@EActivity(R.layout.activity_question)

class QuestionActivity : AppCompatActivity() {


    protected lateinit var questionService : QuestionService
    @InstanceState
    protected lateinit var viewModel : QuestionActivityViewModel

    protected fun onCreate(@BindingObject dataBinder : ActivityQuestionBinding) {
        if(!this::viewModel.isInitialized){
            viewModel = QuestionActivityViewModel(QuestionModel())

            dataBinder.viewModel = viewModel
        }
        questionService = QuestionService()
        getRandomQuestion()

    }
    @Background
    protected fun getRandomQuestion(){
        viewModel.AssignLoading()
        questionService.getRandomQuestion(
            this::onQuestionFound,
            this::onConnectionError,
            this::onServerError)
    }

    @Click(R.id.retry_button)
    protected fun onRetryButtonClicked() {
        getRandomQuestion()

    }

    @UiThread
    protected fun onQuestionFound(question: QuestionModel){
        viewModel.questionModel = question
        viewModel.AssignAskingQuestion()
    }

    @UiThread
    protected fun onConnectionError(){
        viewModel.AssignConnectivityError()
        viewModel.currentError = getString(R.string.text_error_internet)
    }

    @UiThread
    protected fun onServerError(){
        viewModel.AssignServerError()
        viewModel.currentError = getString(R.string.text_error_server)
    }

}
