package ca.csf.mobile2.tp2.question

import android.annotation.SuppressLint
import android.support.v7.app.AppCompatActivity
import android.widget.Button
import android.widget.ProgressBar
import android.widget.TextView
import ca.csf.mobile2.tp2.R
import org.androidannotations.annotations.Background
import org.androidannotations.annotations.EActivity
import org.androidannotations.annotations.UiThread
import org.androidannotations.annotations.ViewById

@SuppressLint("Registered") //Reason : Generated by Android Annotations
@EActivity(R.layout.activity_question)

class QuestionActivity : AppCompatActivity() {

    @ViewById(R.id.choice1_button)
    protected lateinit var choice1Button : Button
    @ViewById(R.id.choice1_textview)
    protected lateinit var choice1TextView : TextView
    @ViewById(R.id.choice1_result_textview)
    protected lateinit var choice1ResultTextView : TextView
    @ViewById(R.id.choice2_button)
    protected lateinit var choice2Button : Button
    @ViewById(R.id.choice2_textview)
    protected lateinit var choice2TextView : TextView
    @ViewById(R.id.choice2_result_textview)
    protected lateinit var choice2ResultTextView : TextView
    @ViewById(R.id.progressBar)
    protected lateinit var progressBar : ProgressBar

    protected lateinit var questionService : QuestionService
    protected lateinit var question : QuestionModel

    @Background
    protected fun getRandomQuestion(){
        questionService.getRandomQuestion(
            this::onQuestionFound,
            this::onConnectionError,
            this::onServerError)
    }

    @UiThread
    protected fun onQuestionFound(question: QuestionModel){
        this.question = question
    }

    @UiThread
    protected fun onConnectionError(){

    }

    @UiThread
    protected fun onServerError(){

    }

}
